import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--epoch', type=int, default=100, help='epoch number')
parser.add_argument('--model_name', type=str, default="EMPNet", help='model name')
parser.add_argument('--lr', type=float, default=5e-5, help='learning rate')
parser.add_argument('--batchsize', type=int, default=4, help='training batch size')
parser.add_argument('--trainsize', type=int, default=256, help='training dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=200, help='every n epochs decay learning rate')
parser.add_argument('--load_mit', type=str, default='./pretrained_params/pvt_v2_b2.pth', help='train from checkpoints') #revised by lzg on 2024.12.17
parser.add_argument('--gpu_id', type=str, default='0', help='train use gpu')
parser.add_argument('--rgb_root', type=str, default='/Space/lzg/multi_view_dataset/TrainingSet(HFUT)/gt_views/', help='the training rgb images root')
parser.add_argument('--mv_root', type=str, default='/Space/lzg/multi_view_dataset/TrainingSet(HFUT)/', help='the training depth images root')
parser.add_argument('--gt_root', type=str, default='/Space/lzg/multi_view_dataset/TrainingSet(HFUT)/train_gts/', help='the training gt images root')
parser.add_argument('--test_rgb_root', type=str, default='/Space/lzg/multi_view_dataset/TestSet/HFUT-Lytro Illum(TIP2020)/test_images/', help='the test gt images root')
parser.add_argument('--test_mv_root', type=str, default='/Space/lzg/multi_view_dataset/TestSet/HFUT-Lytro Illum(TIP2020)/', help='the test gt images root')
parser.add_argument('--test_gt_root', type=str, default='/Space/lzg/multi_view_dataset/TestSet/HFUT-Lytro Illum(TIP2020)/test_gts/', help='the test gt images root')
parser.add_argument('--save_path', type=str, default='./lfsod_cpts/', help='the path to save models and logs')
opt = parser.parse_args()